configType = "standard-overrides"
opDeployerVersion = "0.6.0-rc.3-28a63ff7-2026-01-15T19:40:35Z"
l1ChainID = 11155111
opcmAddress = "0xf0a2e224519e876979ea6b2cd15ef5cc3d6703bd"
fundDevAccounts = false
l1ContractsLocator = "embedded"
l2ContractsLocator = "embedded"

[[chains]]
  id = "0x000000000000000000000000000000000000000000000000000000000001e240"
  baseFeeVaultRecipient = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
  l1FeeVaultRecipient = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
  sequencerFeeVaultRecipient = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
  operatorFeeVaultRecipient = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  gasLimit = 60000000
  operatorFeeScalar = 0
  operatorFeeConstant = 0
  useRevenueShare = true
  chainFeesRecipient = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
  minBaseFee = 0
  daFootprintGasScalar = 0

  [chains.roles]
    l1ProxyAdminOwner = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
    l2ProxyAdminOwner = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
    systemConfigOwner = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
    unsafeBlockSigner = "0x6064CC09a650f418f3baCa5f8c5E91314C92a6f8"
    batcher = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
    proposer = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
    challenger = "0xd0a4104049395f99Cb6fBd6bbbcE2BAA0Ba913a7"
