version: "3.9"

services:
  backend:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  stats:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  user-ops-indexer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
